{
 "title": "Aurora",
 "description": "Simple dashboard to show data from the Aurora exporter ",
 "tags": [
  "aurora",
  "inverter",
  "solar",
  "photovoltaic"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Output power",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aurora_grid_power_reading", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Grid voltage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aurora_grid_voltage_reading", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Grid frequency",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aurora_frequency_reading", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inverter efficiency",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aurora_dc_ac_conversion_efficiency",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Input", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Input voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "aurora_input_1_voltage", "legendFormat": "__auto" },
    { "expr": "aurora_input_2_voltage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Input current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "aurora_input_1_current", "legendFormat": "__auto" },
    { "expr": "aurora_input_2_current", "legendFormat": "__auto" }
   ]
  },
  { "title": "Output", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Output current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "aurora_grid_current_reading", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Output power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "aurora_grid_power_reading", "legendFormat": "__auto" }
   ]
  },
  { "title": "Grid", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Grid voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "aurora_grid_voltage_reading", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Grid frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    { "expr": "aurora_frequency_reading", "legendFormat": "__auto" }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Inverter temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "aurora_inverter_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Booster temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "aurora_booster_temperature", "legendFormat": "__auto" }
   ]
  }
 ]
}